# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ordo-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password!
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ordo
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  database-data:
  mongodb-data:
